services:
  nginx:
    container_name: nginx_container
    image: nginx
    build: ./requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress-php-fpm
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - custom_network
    restart: always

  wordpress-php-fpm:
    container_name: wordpress_container
    image: wordpress-php-fpm
    build: ./requirements/wordpress
    expose:
      - "9000"
    env_file:
      - .env

    volumes:
      - wordpress_data:/var/www/html
    networks:
      - custom_network
    restart: always

  mariadb:
    container_name: mariadb_container
    image: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - wordpress_db_data:/var/lib/mysql
    networks:
      - custom_network
    restart: always

volumes:
  wordpress_db_data:
  wordpress_data:

networks:
  custom_network:
